In [12]:
import numpy as np
import torch 

In [5]:
#create a vector
nv = np.array([ [1,2,3,4] ]) 
print(nv) , print(' ')

[[1 2 3 4]]
 


(None, None)

In [9]:
#transpose it 

print(nv.T), print('')


[[1]
 [2]
 [3]
 [4]]



(None, None)

In [6]:
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]


In [16]:
#repeat for a for a matrix
nM = np.array([ [1,2,3,4],
                [5,6,7,8] 
              ])
print(nM.T), print(' ')
# transpose it 
print(nM.T), print(' ')
#transpose the transpose!
nMT = nM.T
print(nMT.T)


[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]
