In [19]:
import numpy as np
import torch 

In [6]:
#create a vector
nv = np.array([ [1,2,3,4] ]) 
print(nv.T) , print(' ')

[[1]
 [2]
 [3]
 [4]]
 


(None, None)

In [3]:
#transpose it 

print(nv.T), print('')


[[1]
 [2]
 [3]
 [4]]



(None, None)

In [4]:
nvT = nv.T
print(nvT.T)

[[1 2 3 4]]


In [7]:
#repeat for a for a matrix
nM = np.array([ [1,2,3,4],
                [5,6,7,8] 
              ])
print(nM), print(' ')
# transpose it 
print(nM.T), print(' ')
#transpose the transpose!
nMT = nM.T
print(nMT.T)


[[1 2 3 4]
 [5 6 7 8]]
 
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
 
[[1 2 3 4]
 [5 6 7 8]]


In [10]:
#create a vector 
tv = torch.tensor([ [1,2,3,4] ])
print(tv), print(' ')

#transpose it 
print(tv.T), print(' ')

#transpose the transposel
tvT = tv.T
print(tv)

tensor([[1, 2, 3, 4]])
 
tensor([[1],
        [2],
        [3],
        [4]])
 
tensor([[1, 2, 3, 4]])


In [12]:
#repeat for  a matrix 
tM = torch.tensor([[1,2,3,4],[5,6,7,8]])
print(tM), print(' ')

#transpose it 
print(tM.T) , print(' ')
 
#transpose the transpose !

tMT = tM.T 
print(tM)



tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [13]:
#create  a vector
nv1 = np.array([1,2,3,4])
nv2 = np.array([0,1,0,-1])



In [14]:
#dot product via function 
print(np.dot(nv1,nv2))

-2


In [15]:
#dot product via computation
print(np.sum(nv1*nv2))

-2


In [16]:
#create  a vector 
tv1 = torch.tensor([1,2,3,4])
tv2 = torch.tensor([0,1,0,-1])


In [17]:
print(torch.dot(tv1,tv2))

tensor(-2)


In [18]:
print(torch.sum(tv1*tv2))

tensor(-2)


In [21]:
#create some random matrices 
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

In [24]:
print(np.round(A@B ,2)), print(' ')
#print(np.round(A@C ,2)), print(' ')
#print(np.round(B@C ,2)), print(' ')
print(np.round(C.T@A ,2)), print(' ')

[[-2.29 -0.54 -0.42 -1.16 -0.59]
 [ 0.99  0.21 -1.04 -2.77  1.2 ]
 [ 4.48  0.48 -1.35  2.02 -1.6 ]]
 
[[-0.99 -0.6  -1.07 -1.12]
 [ 0.65  1.49 -1.13  0.17]
 [-0.94 -1.75  1.79  0.47]
 [ 1.11 -0.01  0.75 -0.19]
 [ 0.17  0.4  -0.04  0.35]
 [-2.69 -1.47  0.08  0.55]
 [-0.06  0.1  -0.85 -0.76]]
 


(None, None)